trigger: none

pool: Default

stages:
- stage: terraforminitkastatge

  jobs:
  - job: Terraforminitiate
    displayName: Terraform init&all
    
    steps: 
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          terraform init
          terraform fmt
          terraform validate
          terraform plan

- stage: terraformapplystage
  dependsOn: terraforminitkastatge
  jobs:

  - job: Terraformend
    displayName: Terraform apply
    
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          terraform init
          terraform apply


